apiVersion: v1
kind: Pod
metadata:
  name: stream-pod
  labels:
    app: stream
spec:
  containers:
  - name: stream-container
    image: ilyasodysseus/kafka-stream
    imagePullPolicy: Always
    envFrom:
    - secretRef:
        name: btoken
---
apiVersion: v1
kind: Pod
metadata:
  name: filter-pod
  labels:
    app: filter
spec:
  containers:
  - name: filter-container
    image: ilyasodysseus/kafka-filter
    imagePullPolicy: Always
    envFrom:
    - secretRef:
        name: btoken
---
apiVersion: v1
kind: Service
metadata:
  name: visualizer-service
spec:
  type: NodePort
  selector:
    app: visualizer
  ports:
  - protocol: TCP
    targetPort: 5800
    port: 5800
---
apiVersion: v1
kind: Pod
metadata:
  name: visualizer-pod
  labels:
    app: visualizer
spec:
  containers:
  - name: visualizer-container
    image: ilyasodysseus/kafka-visualizer
    imagePullPolicy: Always
